### PR TITLE
Compatibility with Knockout 3.0.0 and DataTables 1.10-dev.

### PR DESCRIPTION
**Pull request by divmgl**
Removes Require.js encapsulation, gives credit to the original author and other minor fixes.

### CODE REVIEW

**Comment by zachpainter77** [comment]
https://github.com/zachpainter77/DatatablesForEach-Custom-Knockout-Binding

**Comment by divmgl** [comment]
Holy jesus this was almost two years ago!

**Comment by JohnBergman** [comment]
And also  https://github.com/JohnBergman/knockout.datatables

It'd be nice to marge all this back into one, I took this project and got it working, at least for my application.

**Comment by divmgl** [comment]
I'm going to on a limb here and assume that no one is maintaining this repo.

**Comment by JohnBergman** [comment]
Looks that way, unfortunately.

**Pull request closed without merging**
